### ISSUE TITLE
#13 breaks pinkie in browsers

### ISSUE THREAD

**Issue by inikulin** [floatdrop/pinkie#14]
#13 aimed to fix browser detection in browserify builds. However, it completely breaks `pinkie` if it was bundled with any other packager, because `global.process` is undefined.

**Comment by floatdrop** [comment]
Fixed in `2.0.3`, thanks!

**Comment by inikulin** [comment]
Wow, that's fast :+1:  Thank you!

**Comment by inikulin** [comment]
Oh, unfortunately 2dbdfb5 will not fix a problem. Since `global` is undefined in browsers `typeof global.process` will still throw. It should be:

``` js
var isNode = typeof global !== 'undefined' && typeof global.process !== 'undefined' && typeof global.process.emit === 'function';
```

**Comment by floatdrop** [comment]
@inikulin thanks again, published a fix for fix :dog:.
